import Foundation

/// A freshly-issued passkey challenge at the service → store boundary.
///
/// Produced by ``Passage/PasskeyService/beginRegistration(with:policy:challengeTTL:)``
/// (or its authentication counterpart) and persisted via
/// ``Passage/PasskeyChallengeStore/createPasskeyChallenge(for:from:)``.
///
/// Mirrors the ``PasskeyCredential`` DTO → ``StoredPasskeyCredential`` pattern:
/// the service emits raw bytes, the store hashes and persists. The raw
/// ``bytes`` never leave the write path of the store implementation — only
/// the hash is written to the row (see ``StoredPasskeyChallenge/challengeHash``).
public struct PasskeyChallenge: Sendable {
    /// Raw challenge bytes as generated by the WebAuthn implementation.
    /// Store implementations SHA-256 these before persisting.
    public let bytes: Data
    /// Ceremony kind this challenge was issued for.
    public let kind: PasskeyChallengeKind
    /// Absolute expiry; computed by the service from `challengeTTL`.
    public let expiresAt: Date

    public init(bytes: Data, kind: PasskeyChallengeKind, expiresAt: Date) {
        self.bytes = bytes
        self.kind = kind
        self.expiresAt = expiresAt
    }
}

// MARK: - Passkey Challenge Kind

public enum PasskeyChallengeKind: String, Sendable {
    case registration
    case authentication
}
