name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }

jobs:
  unit-tests:
    permissions:
      contents: read
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      with_tsan: false
    secrets: inherit

  unit-tests-thread-sanitizer:
    permissions:
      contents: read
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      # --num-workers 1 works around TSan false positives from Swift Concurrency's task allocator
      extra_flags: '--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable --parallel --num-workers 1'
      with_coverage: false
    secrets: inherit

  submit-dependencies:
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' }}
    uses: vapor/ci/.github/workflows/submit-deps.yml@main
    secrets: inherit
